### PR TITLE
Hub and Commands Refactor

### PR DESCRIPTION
**Pull request by TheThirdOne**
- Makes hub.go not have a global hub variable.
- Makes the commands package unnecessary (It was used as a shared type definitions between modules and hub).
- Makes cmd/maestro declare modules used and configuration rather than baton.

### CODE REVIEW

**Comment by TheThirdOne** [comment]
@zachlatta Do you want me to merge hackedu/master in so the circleci will pass?

**Comment by zachlatta** [comment]
@TheThirdOne can you rebase master onto the PR's branch?

On Mon, Aug 17, 2015 at 4:18 PM, Benjamin Landers notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Do you want me to merge
> hackedu/master in so the circleci will pass?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/maestro/pull/23#issuecomment-131989981.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by TheThirdOne** [comment]
@zachlatta Rebased

**Comment by zachlatta** [comment]
Looks great!

**Pull request merged**
